### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::Error: ERROR:  null value in column "address" violates not-null constraint
: INSERT INTO "user_addresses" ("address", "address2", "city", "created_at", "sort_order", "state_code", "updated_at", "user_id", "zip") VALUES 

### ISSUE THREAD

**Issue by ksolo** [Cleveland2030Club/2030Club#50]
Check full details on Airbrake: https://herokuapp7742857herokucom.airbrake.io/groups/52916089?auth_token=5a406320806bccff997ecd161b88089a2d1ecafa

```
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:1164:in `get_last_result'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:1164:in `exec_cache'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:665:in `block in exec_query'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:663:in `exec_query'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:63:in `exec_insert'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:90:in `insert'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/relation.rb:66:in `insert'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/persistence.rb:363:in `create'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/timestamp.rb:57:in `create'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:268:in `block in create'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:403:in `_run__3096466270627802384__create__1374854922486736610__callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:268:in `create'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/persistence.rb:344:in `create_or_update'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:264:in `block in create_or_update'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:414:in `_run__3096466270627802384__save__1374854922486736610__callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:264:in `create_or_update'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/persistence.rb:84:in `save'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/validations.rb:50:in `save'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/attribute_methods/dirty.rb:22:in `save'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:241:in `block (2 levels) in save'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:208:in `transaction'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:241:in `block in save'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:252:in `rollback_active_record_state!'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:240:in `save'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/autosave_association.rb:389:in `save_has_one_association'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/autosave_association.rb:197:in `block in add_autosave_association_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `_run__105079767446507170__create__1374854922486736610__callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:268:in `create'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/persistence.rb:344:in `create_or_update'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:264:in `block in create_or_update'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:447:in `_run__105079767446507170__save__1374854922486736610__callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:264:in `create_or_update'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/persistence.rb:84:in `save'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/validations.rb:50:in `save'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/attribute_methods/dirty.rb:22:in `save'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:241:in `block (2 levels) in save'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:208:in `transaction'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:241:in `block in save'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:252:in `rollback_active_record_state!'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/transactions.rb:240:in `save'
[PROJECT_ROOT]/app/controllers/users_controller.rb:14:in `create'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/base.rb:167:in `process_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:425:in `_run__3360872649553920780__process_action__630188401404649777__callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/callbacks.rb:17:in `process_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/notifications.rb:123:in `block in instrument'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/notifications.rb:123:in `instrument'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/params_wrapper.rb:206:in `process_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/base.rb:121:in `process'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/rendering.rb:45:in `process'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal.rb:203:in `dispatch'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal.rb:246:in `block in action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:73:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:36:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:600:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/etag.rb:23:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/conditionalget.rb:35:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/head.rb:14:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/flash.rb:242:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/cookies.rb:338:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/query_cache.rb:64:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `_run__4337934425518663868__call__1374854922486736610__callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/rack/logger.rb:26:in `call_app'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/rack/logger.rb:16:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/request_id.rb:22:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/runtime.rb:17:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/lock.rb:15:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/static.rb:62:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/engine.rb:479:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/application.rb:220:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/content_length.rb:14:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/rack/log_tailer.rb:17:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/handler/webrick.rb:59:in `service'
[PROJECT_ROOT]/vendor/ruby-1.9.3/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
[PROJECT_ROOT]/vendor/ruby-1.9.3/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
[PROJECT_ROOT]/vendor/ruby-1.9.3/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

**Comment by ghost** [comment]
Not sure what's going on here. Even if you submit the form with all of the address fields blank, the registration succeeds and there's no error, because the empty fields are saved as "" and aren't actually nil. Unless there's some other part of the app that POSTs to this action, all of the fields should just be empty strings rather than nil.

This has been marked as resolved in Airbrake so that if it occurs again we can get the backtrace.
