### ISSUE TITLE
ActionView::MissingTemplate: Missing template home/index, application/index with {:locale=>[:en], :formats=>["application/text", "application/octet-stream"], :handlers=>[:erb, :builder]}. Searched in: * "/app/app/views" 

### ISSUE THREAD

**Issue by ksolo** [Cleveland2030Club/2030Club#58]
Check full details on Airbrake: https://herokuapp7742857herokucom.airbrake.io/groups/65389009?auth_token=5a406320806bccff997ecd161b88089a2d1ecafa

```
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_view/path_set.rb:58:in `find'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_view/lookup_context.rb:109:in `find'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_view/renderer/abstract_renderer.rb:3:in `find_template'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_view/renderer/template_renderer.rb:34:in `determine_template'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_view/renderer/template_renderer.rb:10:in `render'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_view/renderer/renderer.rb:36:in `render_template'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_view/renderer/renderer.rb:17:in `render'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/abstract_controller/rendering.rb:110:in `_render_template'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_controller/metal/streaming.rb:225:in `_render_template'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/abstract_controller/rendering.rb:103:in `render_to_body'
```

**Comment by CoffeeAndCode** [comment]
just cleared the Github auth info in Airbrake so I'll be the creator of issues from now on.  sorry @kmsolorio  :)

**Comment by ksolo** [comment]
Nooooooooooooooo! :)

**Comment by CoffeeAndCode** [comment]
possible solution is creating a Rack middleware to catch these requests early on and handle them (return 406: Not Acceptable)

you can recreate the error with: `curl -H "Accept: application/text" -v http://localhost:3000/`
